package io.github.tatame.aftersale;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

class DemoDatasetEnrichmentHarnessTest {

    private static final Path PROJECT_ROOT = Path.of("").toAbsolutePath();

    @Test
    void mysqlSchemaContainsProductAndOrderItemTables() throws IOException {
        String schema = classpathText("schema-mysql.sql");

        assertThat(schema).contains("CREATE TABLE IF NOT EXISTS products");
        assertThat(schema).contains("product_id VARCHAR(64) PRIMARY KEY");
        assertThat(schema).contains("source_dataset VARCHAR(128) NOT NULL");
        assertThat(schema).contains("CREATE TABLE IF NOT EXISTS order_items");
        assertThat(schema).contains("order_item_id VARCHAR(64) PRIMARY KEY");
        assertThat(schema).contains("FOREIGN KEY (order_id) REFERENCES orders (order_id)");
        assertThat(schema).contains("FOREIGN KEY (product_id) REFERENCES products (product_id)");
    }

    @Test
    void baseMysqlSeedIncludesMinimalProductsAndOrderItems() throws IOException {
        String data = classpathText("data-mysql.sql");

        assertThat(data).contains("INSERT INTO products");
        assertThat(data).contains("P-HEADPHONE-001");
        assertThat(data).contains("manual-minimal-seed");
        assertThat(data).contains("INSERT INTO order_items");
        assertThat(data).contains("OI-O202605130001-1");
        assertThat(data).contains("ON DUPLICATE KEY UPDATE");
    }

    @Test
    void generatedSeedArtifactIncludesOptionalProductsAndOrderItems() throws IOException {
        String generatedSeed = projectText("data/generated/demo_seed_extra.sql");

        assertThat(generatedSeed).contains("Generated by scripts/data/build_demo_seed.py");
        assertThat(generatedSeed).contains("INSERT INTO products");
        assertThat(generatedSeed).contains("INSERT INTO orders");
        assertThat(generatedSeed).contains("INSERT INTO order_items");
    }

    @Test
    void buildScriptProvidesBoundedStandardLibraryGenerationInterface() throws IOException {
        String script = projectText("scripts/data/build_demo_seed.py");

        assertThat(script).contains("argparse.ArgumentParser");
        assertThat(script).contains("--max-orders");
        assertThat(script).contains("--max-products");
        assertThat(script).contains("--max-order-items");
        assertThat(script).contains("--max-tickets");
        assertThat(script).contains("--max-evaluation-cases");
        assertThat(script).contains("utf-8-sig");
        assertThat(script).contains("zipfile");
        assertThat(script).contains("replace(\"'\", \"''\")");
        assertThat(script).doesNotContain("import pandas");
    }

    @Test
    void rawDatasetFilesAreIgnoredButGeneratedArtifactsAreDocumented() throws IOException {
        String gitignore = projectText(".gitignore");
        String rawReadme = projectText("data/raw/README.md");
        String generatedReadme = projectText("data/generated/README.md");

        assertThat(gitignore).contains("data/raw/**/*.csv");
        assertThat(gitignore).contains("data/raw/**/*.xlsx");
        assertThat(gitignore).contains("!data/raw/README.md");
        assertThat(rawReadme).contains("data/raw/orders/");
        assertThat(rawReadme).contains("Do not commit raw datasets");
        assertThat(generatedReadme).contains("demo_seed_extra.sql");
        assertThat(generatedReadme).contains("python scripts/data/build_demo_seed.py");
    }

    @Test
    void datasetMappingDocumentsAllSourcesAndBoundaries() throws IOException {
        String mapping = projectText("docs/data/DATASET_MAPPING.md");

        assertThat(mapping).contains("E-commerce order dataset");
        assertThat(mapping).contains("Chinese e-commerce review dataset");
        assertThat(mapping).contains("Women's clothing feedback dataset");
        assertThat(mapping).contains("Age");
        assertThat(mapping).contains("not used");
        assertThat(mapping).contains("Why Raw Files Are Not Committed");
        assertThat(mapping).contains("default Java evaluation dataset");
    }

    private static String projectText(String path) throws IOException {
        Path file = PROJECT_ROOT.resolve(path);
        assertThat(Files.exists(file)).isTrue();
        return Files.readString(file, StandardCharsets.UTF_8);
    }

    private static String classpathText(String path) throws IOException {
        ClassPathResource resource = new ClassPathResource(path);
        assertThat(resource.exists()).isTrue();
        return new String(resource.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
    }
}
